### PR TITLE
Search OWNERS recursively.

### PR DESCRIPTION
**Pull request by tobie**
/cc @jgraham, @zcorpan, @philip, @gsnedders, @plehegar.

### CODE REVIEW

**Comment by gsnedders** [comment]
Does this not walk all the way up to the filesystem root rather than merely the root of the repo? (I realise realistically that you control the server this runs on and this may not be an issue, but in a theoretical purity way it still matters.)

**Comment by tobie** [comment]
No. The paths are relative to the repo root.

**Comment by tobie** [comment]
And they're fetched using the GH API. There's no local copy of repo content.

**Comment by gsnedders** [comment]
Well then, this LGTM.

**Pull request merged**
